name: "Issue Greeter"
on: [issues]

jobs:
  issue-greeter:
    runs-on: ubuntu-latest
    steps:
      - name: "Greeter"
        uses: avinash201199/Hacktoberfest-Guide@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          message: Welcome to the **Greeter** repo on **Github**.
